var adContent = '';
adContent += '<div id="a-d98142">' + '\n';
adContent += '<!-- AdPlacement : y402311 -->' + '\n';
adContent += '<!-- Yahoo Inc SSP BannerAd DspId:0, SeatId:13123, DspCrId:passback-13252, CrsCrId: -->' + '\n';
adContent += '<!-- var aolSize="300|250" -->' + '\n';
adContent += '<scr' + 'ipt>try{JAC.sandbox.init({w:300,h:250})}catch(e){}</scr' + 'ipt>' + '\n';
adContent += '<i' + 'mg src="https://ap-southeast-1-web-oao.ssp.yahoo.com/admax/adEvent.do?tidi=770829411&amp;dcn=brxd232561&amp;posi=897989&amp;grp=%3F%3F%3F&amp;nl=1675331027468&amp;rts=1675331027252&amp;pix=1&amp;et=1&amp;a=8da040edc0014fc4b177010329300f28&amp;m=aXAtMTAtMjItMTQ4LTIxNQ..&amp;b=MTMxMjM7QVBBQyAtIEFkWCBQYXNzYmFjazs_Pz87Ozs7Y2M2NWJmOTViNjAxNDgzYmExMTkxZTVlZDllYWRjZWI7Mjk0NjMyOTg7MTY3NTMyNjY0ODs7MDs7MDs7cGFzc2JhY2stMTMyNTI7OzE7MTs.&amp;uid=y-RHaMHcNE2rN_cULLfSdETdDIcKge65.aU5InKZLECz8u%7EA&amp;tsrctype=2&amp;xdi=Q2hyb21lIC0gV2luZG93c3xHb29nbGV8TlQgMTAuMHwxN3xEZXNrdG9w&amp;xoi=MHxVU0E.&amp;af=7&amp;brxdPublisherId=28261959434&amp;brxdSiteId=247061&amp;brxdSectionId=85446061&amp;dety=5&amp;us_privacy=1YNN" style="display:none;width:1px;height:1px;border:0;" width="1" height="1" alt=""/>' + '\n';
adContent += '<scr' + 'ipt async src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></scr' + 'ipt>' + '\n';
adContent += '<div id="gpt-passback">' + '\n';
adContent += '  <scr' + 'ipt>' + '\n';
adContent += '    window.googletag = window.googletag || {cmd: []};' + '\n';
adContent += '    googletag.cmd.push(function() {' + '\n';
adContent += '    googletag.defineSlot(\'/61763806/ad-exchange-gpt/apac-nonMail-BTF\', [300, 250], \'gpt-passback\').addService(googletag.pubads()).setTargeting(\'ADPOSITION\', "LREC3").setTargeting(\'SITEID\', "222561");' + '\n';
adContent += '    googletag.pubads().setPrivacySettings({\'restrictDataProcessing\': "0"});' + '\n';
adContent += '    googletag.pubads().set(\'page_url\', "https://tw.stock.yahoo.com/news/chunghwa-telecom-082156107.html");' + '\n';
adContent += '    googletag.enableServices();' + '\n';
adContent += '    googletag.display(\'gpt-passback\');' + '\n';
adContent += '    });' + '\n';
adContent += '  </scr' + 'ipt>' + '\n';
adContent += '</div>' + '\n';
adContent += '<scr' + 'ipt type="text/javascript" src="https://service.idsync.analytics.yahoo.com/sp/v0/pixels?pixelIds=55953,58301,57926,55936,47,55965,58160,58292,55938&referrer=tw.stock.yahoo.com&limit=12&us_privacy=1YNN&js=1&_origin=1&gpp=DBABBgAA~BVoIgAAQ.QAAA&gpp_sid=8&gdpr=0&euconsent="></scr' + 'ipt>' + '\n';
adContent += '<!-- Ads by - Optimized by AdMax from NEXAGE - Thursday, February 2, 2023 at 4:43:47 AM Eastern Standard Time -->' + '\n';
adContent += '</div>' + '\n';
adContent += '<scr' + 'ipt src="https://cdn.js7k.com/ix/talon-1.0.40.js"></scr' + 'ipt>' + '\n';
adContent += '<scr' + 'ipt type="text/javascript">' + '\n';
adContent += 'if (window.OATH && window.OATH.TalonJs) {' + '\n';
adContent += '            window.OATH.TalonJs.init({' + '\n';
adContent += '                lang:"zh-CN",' + '\n';
adContent += '                beaconUrl:"https://beap-bc.yahoo.com/tp?bs=(14nqiem0f(sek$cc65bf95b601483ba1191e5ed9eadceb,st$1675331027252000,li$13123,cr$passback-13252^^APAC - AdX Passback^^0,v$1.0.0,adv$0,pbid$53600,si$222561,dtid$1))&tp=(${talonjsparams},bucket$tnv_stable)",' + '\n';
adContent += '                viewId:"a-d98142",' + '\n';
adContent += '                adSystem:"ONE_MOBILE",' + '\n';
adContent += '                deviceTypeId:1,' + '\n';
adContent += '                publisherId:53600,' + '\n';
adContent += '                configs: {' + '\n';
adContent += '                       adType:"DISPLAY",' + '\n';
adContent += '                   },' + '\n';
adContent += '            });' + '\n';
adContent += ' }' + '\n';
adContent += '</scr' + 'ipt>' + '\n';
document.write(adContent);